version: "3.8"

services:
  design-media:
    image: shivanshukesarwani/design-media:latest  # Use your actual image name here
    container_name: design-media-ui
    ports:
      - "8080:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    depends_on:
      - jellyfin

  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin-server
    ports:
      - "8096:8096"
    volumes:
      - jellyfin_config:/config
      - jellyfin_cache:/cache
      - ./media:/media
    restart: unless-stopped

volumes:
  jellyfin_config:
  jellyfin_cache:
